[phases.setup]
nixPkgs = ["nodejs-18_x"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]  
cmds = ["npm run build"]

[start]
dependsOn = ["build"]
cmd = "npx --yes serve -s build -l $PORT"