[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && python startup.py && uvicorn main:app --host 0.0.0.0 --port $PORT"